### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#105]
I'd love to somehow document how we want to handle releases (mostly so that we can automate the process as much as possible).

Basically what we'll need to do for a release is:

1. Bump the version (`npm version`)
2. Update the changelog (see #103; we can automatically run this as a "post script" for `npm version`)
3. Since `master` is protected we'll need to pull-request the version bump and changelog to master.
4. Tag the release and create a GitHub release
5. Docker files will automatically update once we tag a release in the web-ui repo.

If that is correct, my question would be: Where should we add the tag? We can either:
1. Tag the "bump and changelog branch"
2. Tag `master` after the "bump and changelog" branch was pull-requested and merged (we could even do that automated via GitHub actions, i.e. "everytome a pull request with the `release` label gets merged, create a tag and a release").

I think I'd prefer option 2. since having tags on `master` feels clean to me and a pull-request before a release is probably not the worst thing to do.

Any thoughts? Did I forget anything important?

**Comment by theborakompanioni** [comment]
> I think I'd prefer option 2. since having tags on `master` feels clean to me and a pull-request before a release is probably not the worst thing to do.

full ack.

> Any thoughts? Did I forget anything important?

I think you laid it out great.

Point 5 is maybe a little bit exaggerated as it is just "semi-automated" (which normally means.. not automated at all). A PR to include the newly released UI version is generated by a cron job (so with delay) and one has to create a release manually, which triggers the image build and upload. I think this is acceptable for the first two or three releases - feel free to improve this process as you see fit!
