### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#114]
I am aware that we have the dev docs, which are great, but we should probably also add a `CONTRIBUTING.md` file for people who are new to tracking bugs and stuff like that. 

Here is [a very simple one](https://github.com/thoughtbot/factory_bot_rails/blob/master/CONTRIBUTING.md) that I like. In general, every template that is older than 5 years should be good as a guideline. Most newer templates are as long as they are woke, and I feel like we can do without adding additional wokeness to this world.

**Comment by dnlggr** [comment]
I can take care of that on Monday. 👍
