### ISSUE TITLE
Basic settings screen

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#12]
No designs or mockups of this screen yet, but it could contain something like:

- Web UI settings (denomination, theme, sat symbol)
- JoinMarket settings (txFee, cjFee, cjSize, etc.)

We could think about breaking down the 2nd point—the JoinMarket settings—into three different views, e.g. basic / advanced / expert.

The full `joinmarket.cfg` config file contains many settings and multiple sections (daemon, blockchain, messaging, logging, timeout, policy, payjoin, yield generator), not all of which are immediately relevant to most users.

Clicking the gear icon in the top right will open up this screen.

<img width="183" alt="Screenshot 2022-01-24 at 23 10 06" src="https://user-images.githubusercontent.com/109058/150873369-142ef11a-e834-4098-a4f1-3347b388d319.png">

**Comment by GBKS** [comment]
It would be really great if someone could go through the list of settings and group/prioritize/translate them. Settings pages are visually usually straightforward, but properly describing what each one does, and organizing them in a somewhat intuitive manner is the tricky part.

**Comment by dnlggr** [comment]
I'm going to add a simple settings screen and move whatever settings we currently have there. As discussed in the community call, we can then iterate and add more stuff in future versions.

**Comment by dergigi** [comment]
> properly describing what each one does, and organizing them in a somewhat intuitive manner is the tricky part

@GBKS I completely agree! I'll work on that. Maybe we can even help improve the [JM docs](https://github.com/JoinMarket-Org/joinmarket-clientserver/tree/master/docs), which are ... a bit lacking in that regard 😅

**Comment by dennisreimann** [comment]
Just for reference, this is what the current state looks like.

![image](https://user-images.githubusercontent.com/886/152369350-b0d04726-f5fe-4797-97c7-708185154d5b.png)

@GBKS Right now the options are simple on/off states. It will get more complex when we incorporate the JoinMarket settings.

Is this issue done for now and we will flesh the rest out in another one, when we get to those specific settings?

**Comment by dergigi** [comment]
> Is this issue done for now and we will flesh the rest out in another one, when we get to those specific settings?

Yes, let's do it like that. Tracked #72 for the stuff specific to `joinmarket.cfg`
