### ISSUE TITLE
Fix Raspiblitz integration (auth header)

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#121]
Due to the basic auth setup required in Umbrel, we changed the auth header sent by the UI containing the JoinMarket bearer token to `x-jm-authorization`. See https://github.com/joinmarket-webui/joinmarket-webui/pull/102. That means any webserver hosting the web UI needs to rewrite this header back to `Authorization` before proxying requests to JoinMarket's `jmwalletd` daemon.

The [Raspiblitz NGINX config](https://github.com/rootzoll/raspiblitz/pull/2747) doesn't know about this and therefore doesn't rewrite the authorization header. That means all requests to `jmwalletd` will fail on the RaspiBlitz because `jmwalletd`, of course, expects the token in the `Authorization` header, not in `x-jm-authorization`.

Not sure how/if we can patch this properly. Ideally we fix this on the UI end. Then we don't need to wait for a Raspiblitz version bump to fix the integration script.

What would work (not super clean but it would probably work) is to revert the `x-jm-authorization` header change and go back to sending the bearer token in the standard `Authorization` header. Umbrel would not be affected since that is pinned to the v0.0.3 version. However, Raspiblitz users can update to a newer version by running `config.scripts/bonus.joinmarket-webui.sh update` command.
That of course assumes that we implement #120 before we do the next Umbrel release.

Thoughts on how to best resolve this?

**Comment by dnlggr** [comment]
Ok knowing that there is https://github.com/rootzoll/raspiblitz/pull/2987, we can probably also fix this directly in the Raspiblitz NGINX config. See https://github.com/joinmarket-webui/joinmarket-webui-docker/pull/12/files for reference.

**Comment by dnlggr** [comment]
@dennisreimann Do you think it would make sense to add the fix for this to your existing https://github.com/rootzoll/raspiblitz/pull/2987 Raspiblitz PR to minimize confusion for them, or better have it be two separate PRs?

**Comment by dennisreimann** [comment]
I don't have the time to do so right now – feel free to do so if you can!

**Comment by dnlggr** [comment]
Yep already on it! Just checking how we should handle it logistically. If you think it makes sense to do it in one go I can send you patches, otherwise I'd open a new PR for Raspiblitz.

**Comment by dnlggr** [comment]
Pushed a minimal fix here: https://github.com/rootzoll/raspiblitz/pull/2988

Doesn't enable Basic Auth for Raspiblitz, just makes sure the token gets sent along to `jmwalletd` in the correct header.
