### ISSUE TITLE
Onboarding Flow

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#13]
Cover screen and onboarding flow to be shown upon first use.

See [Figma](https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=267%3A3873) for a rough sketch:

<img width="848" alt="Screenshot 2022-01-24 at 23 37 22" src="https://user-images.githubusercontent.com/109058/150877391-583a7c64-fc2f-4108-aea3-3f42059d4a02.png">

**Comment by GBKS** [comment]
A few things good to cover in an onboarding flow:
- Repeat the primary benefit/features so they are fresh in users minds
- Clearly state anything they need to prepare before use
- Present inputs/options that really need to be set up before using the application for the first time

For JoinMarket, the interactive parts of the onboarding could include:
- Creating a wallet
- Depositing funds

Once funds are deposited, onboarding could continue:
- Guide users through their first use of the maker service
- Or guide them through a pay join

**Comment by secondl1ght** [comment]
I submitted a draft PR #54 for this, I can be assigned to this issue if you guys like what I have done so far.
