### ISSUE TITLE
[Suggestion] use the source code downloaded with git rather than the tar.gz

### ISSUE THREAD

**Issue by openoms** [joinmarket-webui/joinmarket-webui#132]
An interesting issue is that this repo has only merges in the master branch which if done on the GitHub web interface don't have their individual signatures rather just from Github WebFlow. 
This increases trust in GitHub (and the merging user's github credentials).

The release is also signed with the Github WebFlow, but verifying that is still better than just trusting the downloaded file (tar.gz or zip)

In the RaspiBlitz we aim to verify everything possible so will change to 
```
git clone https://github.com/joinmarket-webui/joinmarket-webui
git reset --hard $VERSION
```
to make this possible.

Will aim the same for the JoininBox integration.

**Comment by dnlggr** [comment]
Should I update the Raspiblitz install script to use `git clone` rather than `wget`?

**Comment by openoms** [comment]
> Should I update the Raspiblitz install script to use `git clone` rather than `wget`? 

Will do it myself, no worries. Implemented the `blitz.git-verify.sh` already to do the verification for the other scripts.

**Comment by dnlggr** [comment]
Great! Thanks @openoms.

**Comment by dnlggr** [comment]
I tracked #142 for us to decide on how to go forward with release / commit signatures (GitHub web flow vs. personal signatures).
