### ISSUE TITLE
Clarify default number of counterparties

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#134]
The JM usage guide [mentions a default of 5-7](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/USAGE.md#try-out-a-coinjoin-using-sendpaymentpy) counterparties which is what we implemented. Adam mentioned [on Telegram](https://t.me/JoinMarketWebUI/1220) that it should be 9.

Tracking this here so we don't forget that. I'd say let's err on the side of caution and go with the higher number here.

**Comment by PulpCattel** [comment]
The current default is 8 to 10, https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1199

**Comment by dnlggr** [comment]
Thanks! Looks like the docs are outdated there. Will update!
