### ISSUE TITLE
Show seed option in settings page

### ISSUE THREAD

**Issue by abhiShandy** [joinmarket-webui/joinmarket-webui#136]
User should have an option to verify his seed backup by checking it on settings/wallet page

**Comment by secondl1ght** [comment]
I started working on this but im having a bit of a hard time finding where the seed phrase is stored, can someone point me in the right direction?

**Comment by theborakompanioni** [comment]
> I started working on this but im having a bit of a hard time finding where the seed phrase is stored, can someone point me in the right direction?

A `GET` to `/getseed` - see here: https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/api/wallet-rpc.yaml#L451-L476

**Comment by secondl1ght** [comment]
Thanks, so I will need to manually make a request to api/v1/wallet/{walletname}/getseed? Or is there an API method I can call?

I tried entering it in the browser and get this response:

![image](https://user-images.githubusercontent.com/85003930/156410796-69f60749-214e-402e-a835-5f46ee7b8bac.png)

**Comment by theborakompanioni** [comment]
Currently `/getseed` is not used so you'd have to add it to https://github.com/joinmarket-webui/joinmarket-webui/blob/master/src/libs/JmWalletApi.js - it does not work from the browsers address bar, as you need to send the jwt token in the authentication header. Just add it to the client and it should work.

**Comment by secondl1ght** [comment]
Awesome thanks I will give this a try!

**Comment by secondl1ght** [comment]
Hmm I am still getting the same message in the console even after adding it to the API and calling it from the client with the token and wallet name. I must be doing something wrong, I tried looking at the code for other API calls to see how it works.

**Comment by secondl1ght** [comment]
I tested other API methods using the same auth token using `curl` in the terminal and they are working, but the `getSeed` one is getting the 405 response. Is it possible that we need to add some more code to the backend as well because we have not used this call before?

**Comment by secondl1ght** [comment]
Just giving an update on this: I tried getting the new `getSeed` API working but ran into some difficulties, @theborakompanioni is going to put in a separate PR to get this added because he has it working. After I have that code I will use the new API call to finish this issue, I have the front-end pretty much ready just need the API call working.

**Comment by secondl1ght** [comment]
PR is in #160

**Comment by secondl1ght** [comment]
This has been merged
