### ISSUE TITLE
Development env setup issues

### ISSUE THREAD

**Issue by abhiShandy** [joinmarket-webui/joinmarket-webui#138]
1. `docker/regtest/common.sh` depends on `jq`, so the developer needs to install it from https://stedolan.github.io/jq/download/
2. `APP_USER` environment variable missing in docker setup

**Comment by theborakompanioni** [comment]
> 1. `docker/regtest/common.sh` depends on `jq`, so the developer needs to install it from https://stedolan.github.io/jq/download/

We should probably mention that. You can also use your system package manager. `apt-get install jq` or `dnf install jq`, or what have you.

>     2. `APP_USER` environment variable missing in docker setup

Can you elaborate on that? Two JoinMarket container are started in the regtest setup. Only the second one needs `APP_USER`/`APP_PASSWORD` and these should be defined in current master: https://github.com/joinmarket-webui/joinmarket-webui/blob/master/docker/regtest/docker-compose.yml#L152-L153

**Comment by abhiShandy** [comment]
Something must be missing. I ran `docker-compose build --pull --no-cache` on master branch and it worked

**Comment by theborakompanioni** [comment]
> Something must be missing. [..] and it worked

Sorry to ask for clarification, is this fixed now for you @abhiShandy ?

**Comment by abhiShandy** [comment]
Ya, the docker issue is fixed.

**Comment by theborakompanioni** [comment]
> Ya, the docker issue is fixed.

Nice. Point 1 should also be "fixed" now - a warning is displayed if `jq`, `curl` or `docker` are not installed.
