### ISSUE TITLE
Signing strategy for releases

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#142]
We should decide on how we want releases to be signed. Our options are:

- Tag releases via GitHub and they will be signed using [GitHub's PGP key](https://github.com/web-flow.gpg).
  - Easy to do.
  - Everyone with permissions can release.
  - Increases trust on GitHub.
  - Signatures are as trustworthy as the GitHub credentials of the user tagging the release.
- We pick a person that tags and signs the releases locally and then pushed them to GitHub.
  - Slightly (but not a lot of) more effort.
  - It would probably make sense if only one person does the releases so that there's only one key users need to check the signature of every release.
  - Less trust in GitHub.
  - Safety of the GitHub account credentials are out of the euqation.

I'm leaning towards the latter option. Eventually we should have the same discussion for merges to master as well. E.g. we could squash PRs locally and then push them to master. But let's do this step by step.

See discussion in #132.

**Comment by dnlggr** [comment]
_If no one objects I'd propose the following:_

- With the next release we start with signing tags ourselves (compared to using the GitHub UI to create tags). This has the benefits listed above.
- @dergigi did the release tagging so far and as someone who is known and respected in the community he should continue to do so.
- Instead of creating the release tag using the GitHub UI, he creates it on his machine and pushes it to GitHub via: `git tag -s v0.0.6 && git push origin v0.0.6`. More infos on signing tags and setting up GPG with Git [here](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work).
- He [creates a release from the signed tag using the GitHub UI](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) with changelog, rich title, etc. just like we had it for the past releases.

On the integration side we can then verify that tags have been signed using @dergigi's PGP key. We just need to communicate where the corresponding public key can be fetched from. There's [github.com/dergigi.gpg](https://github.com/dergigi.gpg) for example. Just let us know what you'd prefer @dergigi.

I'll update the docs accordingly once we made this decision. Happy to hear feedback, especially from @dergigi. 🙏 

---

A next step would be merging pull requests from the command line so that every commit on master is signed as well. But this is something for another time I'd say. For now, let's make sure we have properly signed releases starting with the next release.

**Comment by dergigi** [comment]
Sounds good to me! I'll try to do this proper for v0.0.6 🔏 👍
