### ISSUE TITLE
Error when trying to send to Umbrel Jam wallet using QR code 

### ISSUE THREAD

**Issue by merlinoa** [joinmarket-webui/joinmarket-webui#145]
I am seeing this error when attempting to send to my wallet created using the Jam app on Umbrel:

<img src=https://user-images.githubusercontent.com/4030554/156422884-9b9556d4-df16-47ad-b66f-88336a74c82d.png width='230px'/>

I am also getting the same error when attempting to send using the QR code from a Samourai wallet, so it seems to be an issue with the QR code.

**Comment by theborakompanioni** [comment]
> I am also getting the same error when attempting to send using the QR code from a Samourai wallet, so it seems to be an issue with the QR code.

Hey @merlinoa , thanks for reporting!
Yep, you are right. The QR code library will always include params even when they are not defined. Seems it is not compatible with all wallets. It is following [BIP21 style URIs](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki), though - so it might also be good to open an issue on all wallets that do not scan/validate correctly. Nonetheless, guess we should take care of this as well and only include the `value` param if needed. 

Thank you :pray:

**Comment by merlinoa** [comment]
No problem @theborakompanioni . Super excited to use the Umbrel Jam app and Join Market in general.

I forgot to include that the screen shot in my original comment was when sending to Jam from Muun.
