### ISSUE TITLE
Error: No connection to backend: Gateway Time-out.

### ISSUE THREAD

**Issue by bitpaint** [joinmarket-webui/joinmarket-webui#149]
Hey,
Im on a Pie4 with Umbrel using Tor Browser with minimal security settings.
When trying to create a wallet, this happens:

![image](https://user-images.githubusercontent.com/67663265/156582022-ddfb7c8c-53c8-4e1d-9e55-062de6fda951.png)
![image](https://user-images.githubusercontent.com/67663265/156582084-b2b2694f-f525-40ff-9407-7f33e618e56c.png)
![image](https://user-images.githubusercontent.com/67663265/156582368-9ad589d1-cdc4-440c-bbbd-8caef485a758.png)

**Umbrel  logs :**
`jam

jam_1  | Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
jam_1  | To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
jam_1  | ~/.joinmarket/ssl /src/scripts
jam_1  | Generating a RSA private key
jam_1  | ............................................................................................................................................................++++
jam_1  | .........................++++
jam_1  | writing new private key to 'key.pem'
jam_1  | -----
jam_1  | /src/scripts
jam_1  | Auto start: nginx
jam_1  | Auto start: ob-watcher
jam_1  | Auto start: jmwalletd
jam_1  | Creating wallet jam_default if missing...
jam_1  | Loading wallet jam_default...
jam_1  | /usr/lib/python3/dist-packages/supervisor/options.py:474: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
jam_1  |   self.warnings.warn(
jam_1  | 2022-03-03 14:05:03,507 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
jam_1  | 2022-03-03 14:05:03,507 INFO Included extra file "/etc/supervisor/conf.d/jmwalletd.conf" during parsing
jam_1  | 2022-03-03 14:05:03,507 INFO Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
jam_1  | 2022-03-03 14:05:03,508 INFO Included extra file "/etc/supervisor/conf.d/ob-watcher.conf" during parsing
jam_1  | 2022-03-03 14:05:03,508 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
jam_1  | 2022-03-03 14:05:03,517 INFO RPC interface 'supervisor' initialized
jam_1  | 2022-03-03 14:05:03,518 CRIT Server 'unix_http_server' running without any HTTP authentication checking
jam_1  | 2022-03-03 14:05:03,518 INFO supervisord started with pid 8
jam_1  | 2022-03-03 14:05:04,523 INFO spawned: 'jmwalletd' with pid 56
jam_1  | 2022-03-03 14:05:04,529 INFO spawned: 'nginx' with pid 57
jam_1  | 2022-03-03 14:05:04,535 INFO spawned: 'ob-watcher' with pid 58
jam_1  | 2022-03-03 14:05:05,567 INFO success: jmwalletd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
jam_1  | 2022-03-03 14:05:05,568 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
jam_1  | 2022-03-03 14:05:05,569 INFO success: ob-watcher entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
`

After a few minutes, i do see the wallet:
![image](https://user-images.githubusercontent.com/67663265/156586215-e1b6ccc8-1700-4e39-83fe-90fa3a525900.png)

but as pointed out in [Telegram](https://t.me/JoinMarketWebUI/1476): "i never saw this":

![image](https://user-images.githubusercontent.com/67663265/156585727-ae8953be-bafe-4687-be7c-74446dbca80f.png)

**Comment by theborakompanioni** [comment]
Jep, that's a bug - connection error is shown when the backend is not reachable regardless what screen is currently displayed. Should definitely not be this way!
