### ISSUE TITLE
Raspiblitz integration

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#16]
Will probably go live with [Raspiblitz 1.8](https://github.com/rootzoll/raspiblitz/milestone/12).

See the following issues in the [raspiblitz](https://github.com/rootzoll/raspiblitz) repo:

- https://github.com/rootzoll/raspiblitz/pull/2747
- https://github.com/rootzoll/raspiblitz/pull/2987
- https://github.com/rootzoll/raspiblitz/issues/2891

**Comment by dnlggr** [comment]
For the one-click Raspiblitz integration we should probably also setup the `APP_PASSWORD` (`PASSWORD_B` in case of Raspiblitz) similar to as we did it in Umbrel.

**Comment by dergigi** [comment]
Basic integration is done, installation via Menu & WebUI might go live with 1.8.1 according to [rootzoll's comment](https://github.com/rootzoll/raspiblitz/issues/2891#issuecomment-1121581534). 

Closing issue.
