### ISSUE TITLE
Turn display seed phrase on settings page into modal

### ISSUE THREAD

**Issue by secondl1ght** [joinmarket-webui/joinmarket-webui#169]
There was discussion in PR #160 about turning this into a popup modal, I am creating this issue to track further discussion on this. If it is decided that we want this functionality I can look into implementing it.

**Comment by editwentyone** [comment]
here is a preview for a modal 

https://www.figma.com/proto/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?page-id=2850%3A67638&node-id=3283%3A85955&viewport=367%2C48%2C0.57&scaling=min-zoom&starting-point-node-id=3283%3A85955&show-proto-sidebar=1
