### ISSUE TITLE
Umbrel integration

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#17]
Make the JoinMarket Web UI available as an app in the Umbrel app store. 

See [Umbrel App Framework](https://github.com/getumbrel/umbrel/blob/master/apps/README.md)

Timeline
- [x] Create Draft Pull Request in Umbrel Repo (https://github.com/getumbrel/umbrel/pull/1216)
- [x] JM server version `v0.9.5` is released
- [x] Web UI version `v0.0.3` is released
- [x] Release a `standalone` image of server `v0.9.5` and client `v0.0.3`
- [x] Remove `Draft` status of Pull Request in Umbrel Repo
- [x] Pull Request is merged

**Comment by theborakompanioni** [comment]
Currently pushing work to a repo outside the organisation here: https://github.com/theborakompanioni/jm-docker

Will transfer into this repo or a separate repo in organisation `joinmarket-webui` once a common ground has been found for all supported target platforms (umbrel, citadel, etc.).

For umbrel to work without modifying to much scripts manually, the docker images must be publicly available. For now, I'd rather keep it outside the organisation till it becomes stable. Hope this is okay for everyone.

**Comment by theborakompanioni** [comment]
We need to agree on some values before submitting the app to umbrel, namely:

- App name
- Version
- One line description of the app (max 50 characters)
- Summary of the app (50 to 200 words)
- Developer name
- Developer website
- Support link (Link to your Telegram support channel, GitHub issues/discussions, support portal, or any other place where users could contact you for support.)
- Gallery images (Upload 3 to 5 high-quality gallery images (1440x900px) of your app in PNG format)

**Comment by theborakompanioni** [comment]
Suggestion:

>     * App name

joinmarket-webui

>     * Version

Obviously the latest available - v0.0.3 or v0.0.4

>     * One line description of the app (max 50 characters)

"A user-friendly UI for JoinMarket." (34 chars)

(Unfortunately "A web UI for JoinMarket with a focus on user-friendliness." is too long)

>     * Summary of the app (50 to 200 words)

"A web UI for JoinMarket with a focus on user-friendliness. The app provides sensible defaults and is easy to use for beginners while still providing the features advanced users expect." (184 chars)
>     * Developer name
joinmarket-webui organisation

>     * Developer website
https://github.com/joinmarket-webui/joinmarket-webui

>     * Support link (Link to your Telegram support channel, GitHub issues/discussions, support portal, or any other place where users could contact you for support.)
https://github.com/joinmarket-webui/joinmarket-webui/issues

**Comment by dergigi** [comment]
Nice! Regarding version, I'd say we should go for v0.0.3 so we can put some screenshots into the submission that aren't immediately awful 😅

**Comment by theborakompanioni** [comment]
Native test on umbrel in `mainnet` was successful. :heavy_check_mark: 
In order for the integration to move along, we'd need a releasable image.
Releasable image means that both server and client have stable versions - hence we have to wait for the server to progress to `v0.9.5`.
In the meantime tests are done with [joinmarket-webui-dev-standalone:master](https://github.com/joinmarket-webui/joinmarket-webui-docker/pkgs/container/joinmarket-webui-dev-standalone) which contains copies of `master` of both apps at the time the image was created.

**Comment by theborakompanioni** [comment]
Merged. https://github.com/getumbrel/umbrel/pull/1216#issuecomment-1054260173

 :rocket:
