### ISSUE TITLE
Unable to unlock wallet

### ISSUE THREAD

**Issue by merlinoa** [joinmarket-webui/joinmarket-webui#173]
When trying to unlock my wallet I am now getting this error "<wallet name> cannot be created/opened, it is locked."

![Screen Shot 2022-03-11 at 10 40 38 AM](https://user-images.githubusercontent.com/4030554/157900387-136388fb-a387-4c13-b3d4-9fe3b13c9b33.png)

This is the error in the browser console:

![Screen Shot 2022-03-11 at 10 47 01 AM](https://user-images.githubusercontent.com/4030554/157900963-2471cc12-412f-4d55-826e-a268622a25cf.png)

**Comment by yashwanthambati** [comment]
Same error when unlocking on Umbrel

**Comment by theborakompanioni** [comment]
Hmm.. seems related to https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1195 and can be fixed by deleting the log file. This file must be deleted in cases where there was a system or program crash. 
> /unlock will not remove the .lock file from a previously running process. Ensure no other process is running, remove .lock file and try again. If you still get the same I´d check filesystem permissions.

If you need any help, feel free to post in the [Telegram group](https://t.me/JoinMarketWebUI).

**Comment by theborakompanioni** [comment]
The ticket will not be closed immediately, as it would be nice if users don't need to do this manually after a system issue. What can be done about these situations?

e.g. it can definitely be ensured that no lock files exist at startup.. but this only partly solves the problem.

**Comment by theborakompanioni** [comment]
> Hmm.. seems related to [JoinMarket-Org/joinmarket-clientserver#1195](https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1195) and can be fixed by deleting the lock file. This file must be deleted in cases where there was a system or program crash.
> 
> > /unlock will not remove the .lock file from a previously running process. Ensure no other process is running, remove .lock file and try again. If you still get the same I´d check filesystem permissions.

Can reproduce the problem on unclean shutdowns. On umbrel a workaround is to remove the lock file of the wallet, e.g. wallet named "my_wallet".

(Make sure you have **written down your wallet seed** before executing _any_ command)
```sh
docker exec -t jam_jam_1 rm /root/.joinmarket/wallets/.my_wallet.jmdat.lock
```

**Comment by merlinoa** [comment]
Awesome thanks!  I can confirm that running the above docker command resolved the issue for me.  After unlock, everything looks good with my wallet; funds are still showing up in the web UI.

**Comment by theborakompanioni** [comment]
The next server release includes a fix that might be related to this issue: https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1213

**Comment by theborakompanioni** [comment]
Closing the ticket as this is addressed in all integrations using the `v0.0.9` image via [joinmarket-webui-docker/#39](https://github.com/joinmarket-webui/joinmarket-webui-docker/pull/39). Please reopen should this happen again.

**Comment by johnd1984** [comment]
Hello, 

I am having same issue, except I'm running mynode. The power was cut & now i'm getting the error "jmdat cannot be created/opened, it is locked".

I've tried the above command and get the following error "No such container: jam_jam_1"

I've tried switching user permission from admin to bitcoin using "sudo su - bitcoin" - same error

Is there a manual way to just access the folder & delete it - I've looked into the wallet folder, however the lock file doesn't appear to be there.

Failing to delete the lock, can I just sweep funds after the fidelity bond runs out?

Would greatly appreciate any help 

Apologies in advance, only a noob.

**Comment by theborakompanioni** [comment]
> Hello,
> 
> I am having same issue, except I'm running mynode. The power was cut & now i'm getting the error "jmdat cannot be created/opened, it is locked".
> 
> I've tried the above command and get the following error "No such container: jam_jam_1"

As far as I am aware, mynode does not use `docker`, so would you try if the directory `/home/joinmarket/.joinmarket` exists on your file system?
If yes, then try
```
$ rm /home/joinmarket/.joinmarket/wallets/.$wallet_name.jmdat.lock
```
**Note**: Please replace `$wallet_name` with your wallet name, e.g. if it is named "wallet", then use `rm /home/joinmarket/.joinmarket/wallets/.wallet.jmdat.lock`. You might need `sudo` or switch to user `joinmarket` (`sudo su - joinmarket`)

> 
> Is there a manual way to just access the folder & delete it - I've looked into the wallet folder, however the lock file doesn't appear to be there.

Which wallet folder did you look into? `/home/joinmarket/.joinmarket/wallets`?

> Failing to delete the lock, can I just sweep funds after the fidelity bond runs out?

You can always restore the wallet with your seed in other software, such as Sparrow. However, the Fidelity Bond is specific to JM and needs to be spent/unlock from a JM wallet.

> Would greatly appreciate any help

Hope this solves your problems or leads you in the right direction. Do not hesitate to report back if you still have questions or need help.

> Apologies in advance, only a noob.
Nothing of the sort is necessary. JM is not very user-friendly (yet).

**Comment by johnd1984** [comment]
Thanks for speedy reply,

OK that makes with docker & mynode.

I just tried switching to user joinmarket & executing rm command. The lock file doesn't actually exist at /home/joinmarket/.joinmarket/wallets. When I go to Jam UI, the wallet is still inactive - "wallet.jmdat cannot be created/opened, it is locked".

OK so I need to find a way to unlock funds within JM, there's no other way to exit the fidelity bond - like force close a lightning channel?

**Comment by theborakompanioni** [comment]
> Thanks for speedy reply,
> 
> OK that makes with docker & mynode.

Ha, it uses docker after all. Try `docker ps | grep jam` to get the name of the container. And try the original procedure again.

> I just tried switching to user joinmarket & executing rm command. The lock file doesn't actually exist at /home/joinmarket/.joinmarket/wallets. When I go to Jam UI, the wallet is still inactive - "wallet.jmdat cannot be created/opened, it is locked".

Should be mapped to the local directory `/mnt/hdd/mynode/jam/data`. However, try your original approach first. 

> OK so I need to find a way to unlock funds within JM, there's no other way to exit the fidelity bond - like force close a lightning channel?

Yes, there is no other way at the moment. Other wallets will simply "not see" the fidelity bond UTXO.

**Comment by johnd1984** [comment]
Thanks for your help :+1: 
I've posted the question in mynode telegram group
I couldn't find the lock file in "/mnt/hdd/mynode/jam/data" directory either

**Comment by johnd1984** [comment]
is it possible to import wallet to another mynode jam, then spend funds? worst case senario

**Comment by theborakompanioni** [comment]
> is it possible to import wallet to another mynode jam, then spend funds? worst case senario

Next version should be able to import wallets by seed. So yes, it should be possible "soon"™.

**Comment by johnd1984** [comment]
ok thanks :)

**Comment by JeffBorchers** [comment]
I'm having the same issue as John, currently attempting to delete the .lock file but can't find it. 
I can see this directory...
(jmvenv) joinmarket@myNode:~/joinmarket-clientserver/scripts $ /home/joinmarket/.joinmarket/wallets
bash: /home/joinmarket/.joinmarket/wallets: Is a directory
But I can't remove the file. 
(jmvenv) joinmarket@myNode:~/joinmarket-clientserver/scripts $ /home/joinmarket/.joinmarket/wallets
bash: /home/joinmarket/.joinmarket/wallets: Is a directory

**Comment by theborakompanioni** [comment]
Hey @JeffBorchers!

> I'm having the same issue as John, currently attempting to delete the .lock file but can't find it. I can see this directory... (jmvenv) joinmarket@myNode:/joinmarket-clientserver/scripts $ /home/joinmarket/.joinmarket/wallets bash: /home/joinmarket/.joinmarket/wallets: Is a directory But I can't remove the file. (jmvenv) joinmarket@myNode:~/joinmarket-clientserver/scripts $ rm Jam_Wallet.jmdat.lock rm: cannot remove 'Jam_Wallet.jmdat.lock': No such file or directory

I do not have a running mynode instance, but based on your post, it seems you have not executed the command in the right directory. 

**Important**: Make sure you have written down your wallet seed before executing any command!
Also, make sure JM is not running when following the steps.

1. Use `cd` (change directory) to navigate into `/home/joinmarket/.joinmarket/wallets` and `pwd` (print working directory) to verify: 
```shell
joinmarket@myNode:~/joinmarket-clientserver/scripts $ cd /home/joinmarket/.joinmarket/wallets
joinmarket@myNode:~/.joinmarket/wallets $ pwd
/home/joinmarket/.joinmarket/wallets
```

2. Then use `ls -al` (list directory contents) to show the contents of the directory, e.g.:
```shell
joinmarket@myNode:~/.joinmarket/wallets $ ls -al
-rw-------.  1 joinmarket joinmarket     0 Mar 21 02:18 Jam_Wallet.jmdat
-rw-------.  1 joinmarket joinmarket     0 Apr 14 02:20 .Jam_Wallet.jmdat.lock
```

3. If you see a file starting with a dot (`.`) and ending with `.jmdat.lock`, use `rm` to delete the file (and **only** this file!):
```shell
joinmarket@myNode:~/.joinmarket/wallets $ rm .Jam_Wallet.jmdat.lock
```

After that start JM and Jam and try to unlock the wallet.

Hope this is helpful - let us know if it worked and you can access the wallet via the UI again.

**Comment by oskgie** [comment]
thanks for the diligent advice so far regarding this issue. my raspi denies the very last "rm" order for the lock-file. 

first it asks: "remove write-protected regular file... ?"
after confirming it denies with the message: "permission denied"

any idea how to solve this?

**Comment by theborakompanioni** [comment]
> thanks for the diligent advice so far regarding this issue. my raspi denies the very last "rm" order for the lock-file.
> 
> first it asks: "remove write-protected regular file... ?" after confirming it denies with the message: "permission denied"
> 
> any idea how to solve this?

Depends on your setup. Try removing it with the user that owns the file (find out with `ls -l .<wallet_name>.jmdat.lock`) or use `sudo`.

As said above:  Make sure you have written down your wallet seed before executing any command! Also, make sure JM is not running.
