### ISSUE TITLE
Citadel integration

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#18]
Make JoinMarket Web UI available as an app for [Citadel](https://runcitadel.space/).

Probably related to #17, as the underlying architecture should be the same.

**Comment by theborakompanioni** [comment]
Quote from @AaronDewes:
> There is a new version of the app.yml format coming very soon (It's basically finished, it just needs documentation), so I recommend waiting.

Will start as soon as we have confirmation from Aaron.

**Comment by AaronDewes** [comment]
https://github.com/runcitadel/apps/blob/v2/PORTING_APPS.md

Here's a porting guide from docker-compose.yml (Umbrel) to app.yml. Please tell me if you run into any issues.

**Comment by theborakompanioni** [comment]
WIP PR for reference: https://github.com/runcitadel/apps/pull/9

**Comment by theborakompanioni** [comment]
https://github.com/runcitadel/apps/pull/9 (v0.0.3) has not been merged, but implemented separately by @AaronDewes . Closing this now as https://github.com/runcitadel/apps/pull/10 (v0.0.4) was integrated :rocket:
