### ISSUE TITLE
Add confirm dialog when skipping seed backup?

### ISSUE THREAD

**Issue by secondl1ght** [joinmarket-webui/joinmarket-webui#181]
Now that #156 is merged, I was wondering if we should add a 'are you sure?' popup dialog when users click the Skip button and don't confirm their seed phrase.

Could be something like this:

'Are you sure you want to skip seed phrase backup confirmation? You will not be able to recover this wallet and your funds without it. The seed phrase is available to view at any time in the Settings menu.'

What do you guys think?

**Comment by theborakompanioni** [comment]
With the ability to retrieve the seed on the settings page, this does not seem to be much of a concern currently. What about having an eye on messages from users that unintentionally skipped the verification and see if we should adapt the current implementation based on their reviews? What do you think?

**Comment by secondl1ght** [comment]
Yep that sounds good, just wanted to throw the idea out there to see what everyone thought. Should I close this issue then?

**Comment by MaxHillebrand** [comment]
cNACK

I think it's enough to ensure that the skip button is not the default activated when smashing the enter key.

As @theborakompanioni says, mnemonic is retrievable in the settings.

**Comment by dnlggr** [comment]
☝️ Agreed—closing. Thanks for raising the question, though @secondl1ght. Always good to discuss things!
