### ISSUE TITLE
Missing matplotlib python library used by ob-watcher.py

### ISSUE THREAD

**Issue by jase100k** [joinmarket-webui/joinmarket-webui#182]
On JAM v0.0.4 under umbrel,  obwatch complaining that there is missing pip library (matplotlib), refer below errors

2022-03-17 21:47:53,635 [WARNING]  matplotlib not found, charts will not be available. Do `pip install matplotlib` in the joinmarket virtualenv.

This issue exists as the install.sh doesn't appear to install library matplotlib.

**Comment by PulpCattel** [comment]
This is by design, see https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/684
