### ISSUE TITLE
yes.jmdat cannot be created/opened, it is locked.

### ISSUE THREAD

**Issue by Transisto** [joinmarket-webui/joinmarket-webui#191]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/388716/159715430-c3b45003-b39c-4be4-8440-19ed06fdc992.png">

I know I have the right password, At what level is this locked?

**Comment by theborakompanioni** [comment]
Can you see if the solution in #173 solves the problem? 

I will close the issue for now, please feel free to reopen if the error persists.

Also, it would be very helpful if you can append 1) whether it solved your problem, and 2) which steps you took before the issue arose (e.g. starting a maker with unconfirmed coins, etc. - I am currently investigating this issue and any hint towards reproducibility is highly appreciated).
