### ISSUE TITLE
Remove "Skip" button when on mainnet

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#196]
If the seed quiz can be skipped, it will be skipped. I would hide the button when Jam is running on mainnet. Skipping the quiz on any testnet is fine, of course.

I already got one message from a user who played around with Jam on his Umbrel node, didn't write down the seed, and wiped his Umbrel node soon after - forgetting that he had funds in JoinMarket.

This is bad, and I would prefer to err on the side of not burning sats, even though such a sacrifice could be seen as a donation to all 😅

**Comment by theborakompanioni** [comment]
What do you think about allow skipping on `process.env.NODE_ENV === 'development'` only?
Kind of feel like switching behaviour should not be based on the network in use, additionally, we'd save another http request (and all the things that come with it, e.g. showing a loading indicator, etc.)
