### ISSUE TITLE
Change how react-bootstrap components are being imported

### ISSUE THREAD

**Issue by Djo1e** [joinmarket-webui/joinmarket-webui#205]
Per [react-bootstrap's documentation](https://react-bootstrap.github.io/getting-started/introduction/#importing-components) the correct way to import components is `import <Component> from 'react-bootstrap/<Component>'`. 

In the codebase most of the components are being imported as `Import * as rb from 'react-bootstrap'`.

Changing this could reduce the amount of unnecessary code being sent to the client.

**Comment by Djo1e** [comment]
I've replaced all the imports and analysed the bundle via `source-map-explorer`. 

**Original**
<img width="1509" alt="Screenshot 2022-04-03 at 22 16 54" src="https://user-images.githubusercontent.com/34274884/161434863-6a2d9e27-6d90-4d99-8479-f4eca94e4eb5.png">
 
 **Updated**
<img width="1496" alt="Screenshot 2022-04-03 at 22 17 18" src="https://user-images.githubusercontent.com/34274884/161434876-d3186bc4-41fd-4c1b-a98e-19fe8cfbad65.png">

**Conclusion:**
The bundle sizes are pretty much the same. Not what I was expecting. I'm not sure if this is due to `create-react-app`'s code splitting. If anyone else wants to take a look, I can share the changes I've made, maybe I overlooked something. If not, I'll be closing this issue shortly since it might not be an issue after all.

**Comment by theborakompanioni** [comment]
Hey @Djo1e ! Thanks for the effort of looking into it! Even if nothing came of it this time, it's good to know someone has an eye for it! Thank you :pray: 

Really looking forward to what other improvements you come up with :muscle:

**Comment by Djo1e** [comment]
@theborakompanioni This is the [response](https://github.com/react-bootstrap/react-bootstrap/issues/6293#issuecomment-1087481847) I received from one of the maintainer of react-bootstrap. I think we'll be fine both ways. Maybe If we want to stay on the safe side I can raise a PR for this.  I have no strong opinions here. WDYT?

Improvement arriving soon 👀 🚀

**Comment by theborakompanioni** [comment]
>  I have no strong opinions here. WDYT?

Same here. No opinion as of yet. But I see benefits in being specific on imports.. I'd trust the expert, which is you in this case.

> Improvement arriving soon

:rocket:

**Comment by theborakompanioni** [comment]
Closing as #207 has not been merged. Thanks nonetheless @Djo1e! :orange_heart:
