### ISSUE TITLE
Wallet Recovery Via JAM UI 

### ISSUE THREAD

**Issue by Richie-BTC-Rich** [joinmarket-webui/joinmarket-webui#209]
Installing and removing JAM app in umbrel makes you create a new wallet each time.  Is there a wallet recovery method planned , for an existing seed phrase ? 

Umbrel version 0.4.16

**Comment by theborakompanioni** [comment]
He @Richie-BTC-Rich ! Yeah, this is an incredibly important feature. We hope to be able to incorporate it soon. At the moment, the API doesn't provide this functionality yet. As this is tracked in #137, I am closing the issue now. Thank you for reporting :pray:

**Comment by scissorstail** [comment]
Try this with caution.
https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/USAGE.md#recovering-a-wallet-from-mnemonic

**Comment by theborakompanioni** [comment]
> Try this with caution. https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/USAGE.md#recovering-a-wallet-from-mnemonic

:+1:

Also: https://jamdocs.org/FAQ/#can-i-import-an-existing-wallet
