### ISSUE TITLE
Unify CSS

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#217]
CSS is currently a bit wild. We have a global file `index.css`, we have individual (but globally namespaced) `<Component>.css` files and we have (what would be the [correct solution](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/) for namespaced component-level CSS) `<Component.module.css` files.

Since we started splitting up CSS into separate files, we should probably move as much code as possible from `index.css` into CSS modules, and get rid of the `<Component>.css` files.

**Comment by theborakompanioni** [comment]
With #203 applied, it is now possible for `.tsx` files as well. If anybody wants to work on it - let's go :rocket:

**Comment by Djo1e** [comment]
Happy to pick this one up

**Comment by dnlggr** [comment]
> Happy to pick this one up

That would be awesome! 🎉

**Comment by dnlggr** [comment]
Fixed by #230.
