### ISSUE TITLE
Brainstorm: fancy name for the app?

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#22]
Since we want to put this thing in all the nodes, and "JoinMarket Web UI" feels a bit clunky, we might want to use these early days to come up with a fancy name that is short and sweet and cool and all the rest of it. 

The name should be:
* Easy to pronounce
* Unambiguous, both in writing and when you hear it spoken (_not_ "muun with two u's")
* Short enough
* Distinct
* Related to JoinMarket or the concepts that we implement

Examples that I like from the Bitcoin and Lightning world:
* ThunderHub
* SatSale
* Nodl
* Zeus
* Voltage

Yesterday night "Jam" popped into my head, since I've been writing "JM" a lot, and it also works because it's kind of a liquid (which is a good metaphor for what is happening on a technical level, as in "Whirlpool"). You can also think of it as "jamming" the signal that chain analysis tries to decipher.

We could also lean into the "Raspi" theme or the "orange" theme.
<img width="397" alt="Screenshot 2022-01-27 at 10 04 35" src="https://user-images.githubusercontent.com/109058/151326872-cfdcf22f-2d86-4f9d-ad16-b9833234824e.png"> <img width="380" alt="Screenshot 2022-01-27 at 10 05 30" src="https://user-images.githubusercontent.com/109058/151326943-5f6868ca-4560-462b-a608-daf65b4de80a.png">

I also like the "Fusion" concept that came up in [call 4](https://github.com/joinmarket-webui/joinmarket-webui/wiki/community-call-%234). But we might as well make jam 😜

If you have suggestions, drop them!

**Comment by dennisreimann** [comment]
Jam has a nice ring to it and I like the JM connection you mentioned :)

**Comment by AdamISZ** [comment]
Jam is pretty clever. Now you just need to back-ronym in why it's "A" inside of "J" and "M" :)

Err Joinmarket access mechanism .. err ..

**Comment by dergigi** [comment]
Joinmarket's awesome, man.

![Screenshot from 2022-01-28 22-28-22](https://user-images.githubusercontent.com/109058/151623981-4ef8a541-b7e0-4b05-8a43-3804cccd2557.png)

**Comment by dergigi** [comment]
I think sticking with "JoinMarket Web UI" under the hood, and simply "JoinMarket" for the user-facing interfaces is probably fine for now. 

Maybe we'll come up with something better down the road. A rebrand is always possible if something good comes up, and when it comes to package names and the like `joinmarket-webui` should be fine.

Thoughts?

**Comment by theborakompanioni** [comment]
> Thoughts?

I like names that express what their purpose is. That's why I think it's quite suitable. :+1:

**Comment by MaxHillebrand** [comment]
Do you think there will be numerous different UIs for joinmarket in the future, some of them as a webui? If yes, then calling this "first" project `joinmarket-webui` might not be suitable, instead a unique brand, like `Jam` `powered by joinmarket`

**Comment by dergigi** [comment]
> Do you think there will be numerous different UIs for joinmarket in the future, some of them as a webui?

Good point! There is already a 2nd one: https://github.com/getumbrel/umbrel/pull/1170 

Let's see if we can land on a brand/name before `0.1.0`. I'll do my best to define a somewhat sensible roadmap before the next community call tomorrow. Thanks for your input @MaxHillebrand!

**Comment by nopara73** [comment]
Love Jam

**Comment by dergigi** [comment]
Since the issue of naming [came up in the Umbrel PR](https://github.com/getumbrel/umbrel/pull/1216#issuecomment-1053628616), and we got a couple of ACKs in the last call for Jam - as well as in the Telegram community chat - I feel like going with it is at least not wrong! 😅 

JAM, LET'S GOOO! Joinmarket's awesome, man!

**Comment by dnlggr** [comment]
Fine with Jam. 👍 

Thoughts on "JoinMarket Jam" or some way of including JoinMarket in it so people kind of know more or less what it is straight away?

**Comment by dergigi** [comment]
I think having JoinMarket [in the tagline](https://github.com/getumbrel/umbrel/pull/1216/files#diff-7a97633aff18f0ef7dd3fde2856930a95f756d96c5d32a535c5179925e850fe0R483) or description should be enough. I guess most interfaces will have some information in addition to the name, and I would err on the side on keeping the name clean and short and including JoinMarket in said additional information.

In Umbrel, for example, it will show the name and the tagline, like this:

![](https://www.alexshoolman.com/blog/wp-content/uploads/2021/05/Umbrel-BTCPay-Install.jpg)

**Comment by dnlggr** [comment]
Great, glad to replace the gray and generic "webui". 😄 

I'll do a _name update_ PR today. Better get this in as soon as possible. Renaming doesn't get easier with time. 😄

**Comment by dnlggr** [comment]
I would also vote for updating the repo name. GitHub will redirect the old name automatically (`joinmarket-webui/joinmarket-webui` ➡️ `joinmarket-webui/jam`), so no action required for anyone who has a local clone. Everything will just continue to work.

Any objections?

**Comment by secondl1ght** [comment]
I like the idea of having an additional tagline like @MaxHillebrand suggested - 'Jam, powered by joinmarket.' has a nice ring to it and gives credit to the underlying tech. We could include that in various places and still refer to the main app as just Jam.

Glad a name has been decided on though, Jam is definitely easy to say and remember. Do we want to have some new logos designed that incorporate the name in them?

Also @dergigi's comment in the original post 'You can also think of it as "jamming" the signal that chain analysis tries to decipher.' reminded me of a hilarious scene from the movie Spaceballs. 

You guys can check it out if you want a good laugh: https://youtu.be/rGvblGCD7qM but also I think this has some serious meme potential. 

I am not much of a meme maker so if someone else wants to give it a try they can. I think it would be funny and a good way to advertise by sharing on Twitter etc. if we can use this clip as a funny meme about Jam combating chain analysis and KYC... just an idea haha XD.
