### ISSUE TITLE
Developing with umbrel

### ISSUE THREAD

**Issue by chris-pollard** [joinmarket-webui/joinmarket-webui#226]
Hi all, 
Thanks for building this cool UI, and the docs are great. I'm familiar with react, but still pretty early on developing with a bitcoin node. I use umbrel, and just wondering if you could add some developer docs on umbrel too!
Much appreciated,
crispy

**Comment by dnlggr** [comment]
Hi Chris, 

can you please elaborate a bit, I'm not sure I understand what you mean exactly with _docs on umbrel_. You should be able to install Jam directly from the Umbrel app store—no additional setup needed.

**Comment by chris-pollard** [comment]
Hi @dnlggr , I'm not referring to just using Jam on Umbrel, which I've done. I was wondering if I can connect a local version of the web ui (for development) to the Jam instance on Umbrel, like what has been outlined here for RaspiBlitz https://github.com/joinmarket-webui/joinmarket-webui/blob/master/docs/developing.md#running-the-web-ui-locally-and-connecting-to-a-remote-joinmarket-instance

Sorry if I wasn't clear.

**Comment by dnlggr** [comment]
Ok I see. I imagine you could do something similar to what is outlined for the RaspiBlitz where you tunnel request from the local web UI to whatever port/path your Umbrel server is running the [JoinMarket API](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/JSON-RPC-API-using-jmwalletd.md) on. I wouldn't recommend this for development, though. For development, have a look at running JoinMarket locally in regtest through the [development environment](https://github.com/joinmarket-webui/joinmarket-webui/blob/master/docker/regtest/readme.md) we provide.

Keep in mind, Jam is just a web UI for [JoinMarket](https://github.com/JoinMarket-Org/joinmarket-clientserver/).

**Comment by dnlggr** [comment]
I'm closing this issue for now. Don't hesitate to reopen it if you have issues with the regtest development environment.
