### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#24]
I don't have much experience with testing react apps but I think we could at least do some basic UI tests now that we have a working regtest environment.

Not super urgent right now but once the UI is somewhat settled in this is something we could add.

Adding this to the last milestone, feel free to change that!

**Comment by dennisreimann** [comment]
[Cypress](https://www.cypress.io/) is a great tool for that -- but I think that having a test setup based on the regtest env is the bigger hurdle.

**Comment by dergigi** [comment]
Bumped to the next minor release milestone, which is v0.1.0.

Any takers for this one? @theborakompanioni, maybe? 😁

**Comment by theborakompanioni** [comment]
> Any takers for this one? @theborakompanioni, maybe? grin

Affirmative.
