### ISSUE TITLE
Copy for scheduled transactions

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#248]
See https://github.com/joinmarket-webui/joinmarket-webui/pull/242.

Copy is preliminary at the moment and we should think about it again before releasing.

What's currently there:

<img width="619" alt="Screenshot 2022-05-11 at 09 45 49" src="https://user-images.githubusercontent.com/10026790/167796243-4d31de6e-96e0-48ac-bf57-b920f3f1cf9a.png">

**Comment by dergigi** [comment]
Typo: autoamtically -> automatically 😜 

In all seriousness, I'll do my best to get this done today.

**Comment by dnlggr** [comment]
Copy for main Scheduler screen resolved in #257. ✅ 

There's another piece of text in https://github.com/joinmarket-webui/joinmarket-webui/pull/262. Maybe have a quick look at that as well @dergigi. 🙏
