### ISSUE TITLE
Revamp wallet view: display "accounts" as privacy levels

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#27]
See the current design in [Figma](https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=2850%3A68011):

<img width="473" alt="Screenshot 2022-01-28 at 15 53 21" src="https://user-images.githubusercontent.com/109058/151579091-2be94eed-603f-4941-b34f-26c2d393154f.png">

In short:
* Hide derivation paths and addresses from the user
* What is currently called "Account 0" is the lowest level, i.e. "one shield"

We can add the complexity that this will hide later on if we like, but the current view is all kinds of confusing, so this would be an improvement. 

Note that this concept/design is by no means final, since we can't always map "privacy level" to "accounts" (mixdepths) in a truthful one-to-one manner. But again: it's a big improvement from the current UI and should be easier to understand than mixdepths.

**Comment by dnlggr** [comment]
Regarding the _Overall Privacy Level_ indicator:

<img width="262" alt="Screenshot 2022-02-04 at 12 42 37" src="https://user-images.githubusercontent.com/10026790/152523447-78d5d2d4-e574-458e-8e3f-fd3b6e0dc9ff.png">

I'm using "privacy level" and "mixdepth" interchangeably here for simplicity.

I like the idea of an overall privacy level to motivate users. I'm wondering how should we compute this, though.
My first thought was simply computing a weighted average over all coins in all privacy levels. While implementing I started to doubt that this makes sense.
My thinking is this: Let's say you have one coin with privacy level 1️⃣ and another coin with privacy level  5️⃣ .
The overall average privacy level would then be 3️⃣ .

But if you spend the coin with privacy level 1️⃣ you don't get privacy as if it were a coin with privacy level level 3️⃣ . All you get is privacy level 0️⃣ . This might be confusing for the user who I could assume that the overall privacy level applies to all coins when in reality it is just the average but doesn't relate to the actual privacy of individual coins.
