### ISSUE TITLE
bug: cheatsheet modal gets cutoff at the bottom

### ISSUE THREAD

**Issue by secondl1ght** [joinmarket-webui/joinmarket-webui#275]
I just pulled the latest and ran locally and on my screen The Cheatsheet modal is cutoff on the bottom, see screenshot below:

![image](https://user-images.githubusercontent.com/85003930/168724243-266a1b79-6cb4-44f5-8378-57a28e3feda3.png)

**Comment by dnlggr** [comment]
This is by design I think. It's not cutoff (the text is always readable) the UI element just extends all the way to the bottom.

<img width="1749" alt="Screenshot 2022-05-17 at 09 54 33" src="https://user-images.githubusercontent.com/10026790/168759323-37bbd565-9ee0-4b21-b15c-803f96765dcb.png">

**Comment by secondl1ght** [comment]
Ok this doesn't look good imo.

**Comment by theborakompanioni** [comment]
> Ok this doesn't look good imo.

To be fair, the visual transition effect is quite fancy, isn't it? :wink: 
Jokes aside, instead of just saying that something is wrong, it would help in general if you'd give a reason or two stating why you don't like it or even make suggestions for improvement!
This is universally true for any comment on the interwebs (and especially regarding software projects) : D

**Comment by editwentyone** [comment]
the idea is: its a piece of paper sliding from the bottom and overlaying a screen without being as boring as a modal ;)

**Comment by secondl1ght** [comment]
The reason I don't like it is because it looks like it is being cutoff and there may be more info missing, I think it would look better centered on the screen so you know you are viewing the entire modal. But that's just what I thought when I was interacting with it, sounds like others like it so that's good.

**Comment by theborakompanioni** [comment]
> The reason I don't like it is because it looks like it is being cutoff and there may be more info missing, I think it would look better centered on the screen so you know you are viewing the entire modal. But that's just what I thought when I was interacting with it, sounds like others like it so that's good.

Happy for your all your inputs and thoughts.
Have you played around with different styles?

Would you think something like this is better suited?
<img src="https://user-images.githubusercontent.com/3358649/169006215-f77bffd0-d50c-4fe2-98d9-8b0034e5804f.png" width=400 />

**Comment by dnlggr** [comment]
> the idea is: its a piece of paper sliding from the bottom and overlaying a screen without being as boring as a modal ;)

I like that as well! I think it has a real "sheety" feel to it. Imo we should keep it that way.

**Comment by editwentyone** [comment]
agree, its a detail also I ended the list numbers with a checkmark so its clearer the list ended. https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/?node-id=2850%3A67638

**Comment by editwentyone** [comment]
thanks for the feedback, lets also add a little more spacing. on the other hand: we hope to remove the cheatsheet in a future release because the app itself gets better and easier to use.
