### ISSUE TITLE
Improve connection indicator

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#28]
We have a connection indicator already, but it only shows up if the UI can't connect to the API. It currently looks like this:
<img width="158" alt="Screenshot 2022-01-28 at 17 07 06" src="https://user-images.githubusercontent.com/109058/151581234-a56f6c14-e8a6-481e-94fb-26b823155fd0.png">

Once a connection is established, it will look like this:
<img width="171" alt="Screenshot 2022-01-28 at 17 07 16" src="https://user-images.githubusercontent.com/109058/151581399-25ea5a8a-04dd-44c5-a840-8b396c7f7622.png">

I'd propose a connection indicator either in the header or the footer, something like a simple green/red dot and some text that says "Connected" or "Disconnected".

**Comment by secondl1ght** [comment]
I put in a PR for this #55
