### ISSUE TITLE
ui: hint about creating wallet taking some time

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/joinmarket-webui#294]
Add a message hinting that creating a wallet can take some time.

> a spinner and a message that this can take up to 2 to 5 minutes is a must in that case. 

[Figma](https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/?node-id=3283%3A67347)
<img width="684" alt="image" src="https://user-images.githubusercontent.com/96262473/170188440-61ad07a1-67cb-4e35-9901-c2a460db1042.png">

_Originally posted by @editwentyone in https://github.com/joinmarket-webui/joinmarket-webui-docker/issues/34#issuecomment-1136750359_

**Comment by dnlggr** [comment]
> this can take up to two to five minutes.

Maybe this reads better: "This can take a couple of minutes."

---

Generally, is there something we can do to make this faster? Does this take the same amount of time on e.g. Joininbox?

**Comment by dnlggr** [comment]
> this can take up to two to five minutes.

Maybe this reads better: "This can take a couple of minutes."

---

Generally, is there something we can do to make this faster? Does this take the same amount of time on e.g. Joininbox?
