### ISSUE TITLE
footer: move version to left side

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#312]
As briefly mentioned in [Call 16](https://github.com/joinmarket-webui/joinmarket-webui/wiki/Community-Call-%2316)

<img width="205" alt="Screenshot 2022-06-06 at 10 22 34" src="https://user-images.githubusercontent.com/109058/172867426-cdec76d0-3892-423c-a158-589d71297fd3.png">

**Comment by theborakompanioni** [comment]
Closing this based on the conversations here and in the PR. Reopen if it becomes relevant again.
