### ISSUE TITLE
Question: Lock wallet flow

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/joinmarket-webui#323]
UI flow to lock a wallet does not feel very natural.
Currently, you have to go to `Settings` > `Switch wallets` > `Lock wallet`.

Would it be okay to introduce a "Lock/Leave wallet" functionality directly on the Settings page?

**Comment by dnlggr** [comment]
Agreed. Adding this right now.

**Comment by editwentyone** [comment]
like that? 

https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/?node-id=3283%3A85955

<img width="597" alt="image" src="https://user-images.githubusercontent.com/96262473/174605276-f422b2c3-f610-443b-934e-574e6c10d039.png">
