### ISSUE TITLE
Maker service not stopping

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/joinmarket-webui#34]
As a user with a balance of zero, when I start the Maker service it shows the error `Maker could not start, no coins.` (request results in `409 Conflict`).
However, the service starts anyway. When subsequently clicking "stop", it will display a success message `The service is stopping.` (request is even resulting in `202 Accepted`).
Nevertheless, the service is not stopped and will stay this way indefinitely.

I do not know if we can do anything on the client, as this seems to be a server issue.
Just want to keep it here as reference - I will investigate the server code and open an issue in their repo if needed.

**Comment by dennisreimann** [comment]
There's some more info in the issue I posted here: JoinMarket-Org/joinmarket-clientserver#1120

**Comment by theborakompanioni** [comment]
Fixed as https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1169 is merged. Eagerly awaiting v0.9.5 :rocket:
