### ISSUE TITLE
App stops responding

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/joinmarket-webui#35]
After opening and closing the wallet a few times the service stops responding and no further interaction is possible (api stops responding).
This happens rather quickly and can be reproduced on my side after locking/unlocking the wallet four to five times.

In this state, when reloading the page, the app stops rendering completely.

Server logs do not give a strong hint about what might be wrong.
```sh
> root@edd0ae308a67:~/.joinmarket/logs# tail -f jmwalletd_stdout.log -n 200
```
```
<Request at 0x7f7e2d385b80 method=POST uri=/api/v1/wallet/t.jmdat/unlock clientproto=HTTP/1.1> [...]
2022-02-01 10:49:37,349 [DEBUG]  rpc: listaddressgroupings []
2022-02-01 10:49:37,353 [INFO]  Detected new wallet, performing initial import
2022-02-01 10:49:37,353 [DEBUG]  requesting detailed wallet history
2022-02-01 10:49:38,254 [DEBUG]  rpc: listlabels []
2022-02-01 10:49:38,255 [DEBUG]  rpc: getaddressesbylabel ['joinmarket-wallet-d4ef50']
2022-02-01 10:49:38,273 [DEBUG]  got used indices: {0: [0, 0, 0, 0], 1: [0, 0, 0, 0], 2: [0, 0, 0, 0], 3: [0, 0, 0, 0], 4: [0, 0, 0, 0]}
2022-02-01 10:49:38,352 [DEBUG]  rpc: listlabels []
2022-02-01 10:49:38,354 [DEBUG]  rpc: getaddressesbylabel ['joinmarket-wallet-d4ef50']
2022-02-01 10:49:38,362 [DEBUG]  Wallet successfully synced
2022-02-01 10:49:38,363 [DEBUG]  rpc: listunspent []
2022-02-01 10:49:38,371 [DEBUG]  bitcoind sync_unspent took 0.008394718170166016sec
2022-02-01 10:49:38,382 [INFO]  Starting transaction monitor in walletservice
<Request at 0x7f7e2d3f6c40 method=GET uri=/api/v1/wallet/t.jmdat/display clientproto=HTTP/1.1> [...]
<Request at 0x7f7e2d3f6df0 method=GET uri=/api/v1/wallet/t.jmdat/lock clientproto=HTTP/1.1> [...]
<Request at 0x7f7e2d396a00 method=POST uri=/api/v1/wallet/t.jmdat/unlock clientproto=HTTP/1.1> [...]
2022-02-01 10:49:44,289 [DEBUG]  rpc: listaddressgroupings []
2022-02-01 10:49:44,292 [INFO]  Detected new wallet, performing initial import
2022-02-01 10:49:44,292 [DEBUG]  requesting detailed wallet history
2022-02-01 10:49:45,208 [DEBUG]  rpc: listlabels []
2022-02-01 10:49:45,219 [DEBUG]  rpc: getaddressesbylabel ['joinmarket-wallet-d4ef50']
2022-02-01 10:49:45,239 [DEBUG]  got used indices: {0: [0, 0, 0, 0], 1: [0, 0, 0, 0], 2: [0, 0, 0, 0], 3: [0, 0, 0, 0], 4: [0, 0, 0, 0]}
2022-02-01 10:49:45,309 [DEBUG]  rpc: listlabels []
2022-02-01 10:49:45,311 [DEBUG]  rpc: getaddressesbylabel ['joinmarket-wallet-d4ef50']
2022-02-01 10:49:45,318 [DEBUG]  Wallet successfully synced
2022-02-01 10:49:45,319 [DEBUG]  rpc: listunspent []
2022-02-01 10:49:45,326 [DEBUG]  bitcoind sync_unspent took 0.00782322883605957sec
2022-02-01 10:49:45,342 [INFO]  Starting transaction monitor in walletservice
```

~~Maybe `Starting transaction monitor in walletservice` causes problems on the server, but this is just unfounded speculation.
Seems like there cannot be much done on the client side, except for better handling of the unresponsiveness of the server maybe.~~

**Comment by dnlggr** [comment]
Linking #28 here.

**Comment by theborakompanioni** [comment]
> Linking #28 here. If the server is not responsive we should communicate that in the UI.
Yes, the thing is in this state the server seems to respond to some `/session` requests ... leading to the funny behaviour, that on every second refresh, the site stays blank. However, when it loads (`200 OK` from `/session`), no interaction is possible (all other requests do not come back - not even timeout).

**Comment by theborakompanioni** [comment]
There might really be a problem on our side here. Opening the app in another browser works fine again. Reproducible on Chromium and Firefox here.

**Comment by dergigi** [comment]
I was able to reproduce this issue with Firefox 96.0.3 (64-bit) on current master, commit 0db76d9.

Wallet ended up in a locked state, UI showed the following:
<img width="467" alt="Screenshot 2022-02-01 at 23 33 53" src="https://user-images.githubusercontent.com/109058/152063143-bc3d226a-89b1-4ff9-82dc-cfd38f78fe38.png">

As @theborakompanioni reported, using another session (incognito window or Chromium) worked, but the wallet was locked so I couldn't do much.

**Comment by dnlggr** [comment]
> There might really be a problem on our side here. Opening the app in another browser works fine again. Reproducible on Chromium and Firefox here.

I have the feeling (in general, not just related to this issue) that the entire app is much more stable when I use it on Safari. On Firefox I get locked out of the wallet _a lot_. Strange stuff. 🤔

**Comment by dnlggr** [comment]
Yeah I'm pretty sure this is a client side issue as well. On Safari I can open/lock the wallet 20+ times—no problem. On Firefox, as you guys already mentioned, 4,5 times max until requests just stop returning anything. Super strange.

**Comment by dnlggr** [comment]
I think it might be related to the websockets. If I remove the websocket code (see diff) then I can't reproduce this anymore.

Can you confirm this @theborakompanioni? I'll look into it a bit more in the meantime.

``` diff
diff --git a/src/components/App.jsx b/src/components/App.jsx
index 2122687..6f73305 100644
--- a/src/components/App.jsx
+++ b/src/components/App.jsx
@@ -19,41 +19,41 @@ export default function App() {
   const [makerRunning, setMakerRunning] = useState()
   const [connectionError, setConnectionError] = useState()
   const [coinjoinInProcess, setCoinjoinInProcess] = useState()
-  const websocket = useRef(null)
+  // const websocket = useRef(null)
 
   const startWallet = useCallback(
     (name, token) => {
       setSession(name, token)
       setCurrentWallet({ name, token })
 
-      const { protocol, host } = window.location
-      const scheme = protocol === 'https:' ? 'wss' : 'ws'
-      websocket.current = new WebSocket(`${scheme}://${host}/ws/`)
-
-      websocket.current.onopen = () => {
-        console.debug('websocket connection openend')
-        websocket.current.send(token)
-      }
-
-      websocket.current.onerror = (error) => {
-        console.error('websocket error', error)
-      }
-
-      websocket.current.onmessage = (event) => {
-        // For now we only have one message type, namely the transaction notification:
-        // For now, note that since the `getUtxos` function is called on every render of
-        // the display page, we don't need to somehow use this data other than as some
-        // kind of popup/status bar notifier.
-        // In future it might be possible to use the detailed transaction deserialization
-        // passed in this notification, for something.
-        const wsdata = JSON.parse(event.data)
-        console.debug('websocket sent', wsdata)
-      }
-
-      const wsCurrent = websocket.current
-      return () => {
-        wsCurrent.close()
-      }
+      // const { protocol, host } = window.location
+      // const scheme = protocol === 'https:' ? 'wss' : 'ws'
+      // websocket.current = new WebSocket(`${scheme}://${host}/ws/`)
+
+      // websocket.current.onopen = () => {
+      //   console.debug('websocket connection openend')
+      //   websocket.current.send(token)
+      // }
+
+      // websocket.current.onerror = (error) => {
+      //   console.error('websocket error', error)
+      // }
+
+      // websocket.current.onmessage = (event) => {
+      //   // For now we only have one message type, namely the transaction notification:
+      //   // For now, note that since the `getUtxos` function is called on every render of
+      //   // the display page, we don't need to somehow use this data other than as some
+      //   // kind of popup/status bar notifier.
+      //   // In future it might be possible to use the detailed transaction deserialization
+      //   // passed in this notification, for something.
+      //   const wsdata = JSON.parse(event.data)
+      //   console.debug('websocket sent', wsdata)
+      // }
+
+      // const wsCurrent = websocket.current
+      // return () => {
+      //   wsCurrent.close()
+      // }
     },
     [setCurrentWallet]
   )
@@ -63,12 +63,12 @@ export default function App() {
     setCurrentWallet(null)
     setCurrentWalletInfo(null)
 
-    if (websocket) {
-      websocket.current.onclose = () => {
-        console.debug('websocket connection closed')
-      }
-      websocket.current.close()
-    }
+    // if (websocket) {
+    //   websocket.current.onclose = () => {
+    //     console.debug('websocket connection closed')
+    //   }
+    //   websocket.current.close()
+    // }
   }
 
   useEffect(() => {
```

**Comment by dnlggr** [comment]
I'm pretty confident that the websockets somehow cause this problem. Not sure why and how but if I remove the websocket code I consistently cannot reproduce it anymore.

Do the websockets work for anyone? For me, I always get the following errors after a couple of seconds:

> Firefox can’t establish a connection to the server at ws://localhost:3000/ws/.
>
> websocket error 
error { target: WebSocket, isTrusted: true, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }

I know it's not really solving anything but since we aren't using the websockets anyway ([they just log whatever data they receive](https://github.com/joinmarket-webui/joinmarket-webui/blob/0db76d99ddffb6ba451ff98601660ffa173a0110/src/components/App.jsx#L49)), what if we simply remove them for now and try to add them back later when we need them? First, I'd love to know if you guys can reproduce my findings though.

**Comment by theborakompanioni** [comment]
> First, I'd love to know if you guys can reproduce my findings though.

Can confirm the problem is solved when applying your patch, really great find!
Since we do not need it, I agree with your opinion of removing it :heavy_check_mark:
