### ISSUE TITLE
Question: Prevent certain characters in wallet names?

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/joinmarket-webui#352]
e.g. Currently it is possible to create a wallet consisting of only whitespaces. See screenshots.
What do you think? Should certain characters be declined by the client, or should this responsibility be delegated to the server?

## :camera_flash: 
<img src="https://user-images.githubusercontent.com/3358649/176040796-547a7851-d5d9-4f9f-80fc-16d0705f4aaa.png" width=400 /> <img src="https://user-images.githubusercontent.com/3358649/176040768-3b437751-a9ca-4d0a-99b0-a1c6907400cb.png" width=400 />

**Comment by theborakompanioni** [comment]
Currently, wallet names containing `#` or `?` will lead to errors till https://github.com/joinmarket-webui/joinmarket-webui/pull/389 is applied. See also https://github.com/joinmarket-webui/joinmarket-webui/issues/387.

**Comment by dnlggr** [comment]
I feel like this is something the server should have rules for. If the server allows for such names we can't really be sure that users won't create wallets outside of Jam so we have to be able to handle those anyway. Or at least gracefully fail if we see them and can't handle them otherwise.
