### ISSUE TITLE
De-emphazise creating a second fidelity bond

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#365]
The UI currently doesn't inform the user that it's mostly useless to create a second fidelity bond. JM will always advertise the most valuable one so while you can use a larger second FB to overwrite the first one -- this is not a common use case so we should de-emphazise doing so in the UI.

**Comment by editwentyone** [comment]
I would say that we could hide that under advanced and make a note there, that describes how JM would always take the most valuable one
