### ISSUE TITLE
Visually warn the user when selecting non cj-out UTXOs for fidelity bonds

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#369]
Similarly to how we show a red button when sending a transaction without collaborators we could indicate "danger" when creating a FB from a non cj-out UTXO.
In the future we might want to offer doing a collaborative transaction to an intermediate address before funding the FB from there. See #367.

**Comment by theborakompanioni** [comment]
Blocked by https://github.com/joinmarket-webui/joinmarket-webui/issues/375
