### ISSUE TITLE
Correctly fetch status for fidelity bond UTXOs 

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#375]
For some reason, when loading UTXOs from the backend, a UTXOs `status` (e.g. `cj-out`) is not included. The `status` field seems to only be there for addresses when fetching the entire wallet. So we somehow have to fetch the whole wallet and then match UTXOs to addresses to find out which status a UTXO has.

See https://github.com/joinmarket-webui/joinmarket-webui/pull/361#discussion_r914678203 for more details.

**Comment by theborakompanioni** [comment]
Done in https://github.com/joinmarket-webui/joinmarket-webui/pull/383.
