### ISSUE TITLE
Show address reuse warning

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#404]
Currently, it is not only possible to reuse addresses in Jam, there is also no indication that there's anything wrong with that. We probably want to, at the very least, show a warning. We should be able to easily do this for all "internal" Jam addresses, i.e. if you accidentally paste the same address twice (e.g. to fund a jar with multiple transactions).

It would also be good to show a warning in general, for any address, but we can't query the backend for that as of now.

We could also think of a "strict" setting that doesn't allow any reuse at all, no matter what.

**Comment by MaxHillebrand** [comment]
This warning should also be in the receive page.

Warning in the send tab only solves in-wallet self spends, but most cases are when sending from external wallets.

Hiding addresses that have received a coin might be an option.

**Comment by dnlggr** [comment]
> This warning should also be in the receive page.

The receive page will only ever show you new addresses. We query the backend for a new address on every render of the page.
