### ISSUE TITLE
Navbar improvements

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#41]
- [x] Improve mobile layout: https://github.com/joinmarket-webui/joinmarket-webui/pull/29#issuecomment-1027185900 fixed in: https://github.com/joinmarket-webui/joinmarket-webui/pull/44
- [x] Change mobile menu to offcanvas drawer: https://github.com/joinmarket-webui/joinmarket-webui/pull/29#issuecomment-1027185900 fixed in: https://github.com/joinmarket-webui/joinmarket-webui/pull/44
- [x] Show wallet name vertically centered when balance is not shown and animate the transition when the balance is eventually shown: https://github.com/joinmarket-webui/joinmarket-webui/pull/29#issuecomment-1027027362

**Comment by dergigi** [comment]
I think all of that is done, correct? I'll close the issue now. Feel free to re-open if necessary.

**Comment by dnlggr** [comment]
The last one is not done. Not sure why it was checked. 🤷‍♂️
