### ISSUE TITLE
block bei telegram gruppe because of question

### ISSUE THREAD

**Issue by LupusPluvia** [joinmarket-webui/joinmarket-webui#423]
Hello, the telegram group blocked me just because I asked a question. I ask him what does it have to do with the glasses, it's important

**Comment by theborakompanioni** [comment]
Just to be clear: There is simply no way you got blocked just for asking a question. Probably for spamming or posting a dodgy link.
Please behave.

ping @dergigi

**Comment by LupusPluvia** [comment]
I didn't share a link I just asked what it had to do with the glasses and hey presto I was tied

**Comment by theborakompanioni** [comment]
Might have been a mistake then. Apologies if this was the case.

**Comment by LupusPluvia** [comment]
happens. but can you tell me what the glassers are doing where the btc are stored. because it all goes into glass zero. which ones are important or are they all important and should be equally full?

**Comment by theborakompanioni** [comment]
Fair question. The documentation will be improved in the future.

From [jamdocs.org](https://jamdocs.org/glossary/#j) (work in progress):
> In Jam, a "jar" is a container that holds some [sats](https://jamdocs.org/glossary/#sats) of yours. Jars exist to segregate your sats into multiple buckets that are disconnected from each other, which aids privacy. To not risk any privacy degradation, you can only spend from one jar at a time.
>
> There are 5 jars by default. The default jar to receive funds is Jar #0.

Also:
> What we call "jars" are usually called "mixdepths" in JoinMarket. They are also referred to as "pockets" and "accounts" in some of the older parts of the JoinMarket documentation.

None of them is more important than the other. Jar#0 is just the one you should use for funding by convention. They do not need to be equally full. Whenever you "jam" your funds will run through the jars by performing [CoinJoins](https://jamdocs.org/glossary/#c), making it harder for outside observers to violate your privacy.
> CoinJoins break the [common input ownership heuristic](https://jamdocs.org/glossary/#common-input-ownership-heuristic) that is used by chain analysis companies to de-anonymize actors.

You can also do single CoinJoins on the Send page. Make sure to never ever combine funds from different jars again at a later point.

If you want to dive deeper into the inner workings of JoinMarket, see [joinmarket-clientserver#v0.9.6/docs](https://github.com/JoinMarket-Org/joinmarket-clientserver/tree/v0.9.6/docs).

**Comment by LupusPluvia** [comment]
thanks, now I can understand it better
