### ISSUE TITLE
Show content placeholders while loading 

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#56]
See https://github.com/joinmarket-webui/joinmarket-webui/pull/51#issuecomment-1030399995.

We could show loading placeholders like [these](https://zalog.ro/placeholder-loading/) (obviously adapted to fit the layout of our UI) while content is fetched to make loading seem faster and more smooth.

<img width="594" alt="Screenshot 2022-02-07 at 10 56 29" src="https://user-images.githubusercontent.com/10026790/152765736-1d4ba8d0-8079-4d9c-8217-e5262670f305.png">

**Comment by secondl1ght** [comment]
Do you know which areas you would want these placeholders? I haven't tested all the app functionality yet but so far it seems pretty fast and there are loading spinners in some places. Would you want to replace the loading spinners with these placeholders?

**Comment by Djo1e** [comment]
@secondl1ght I think we can add content placeholders for the `Send` and `Receive` sections. It would reduce the jitter and look better overall IMO. Also the same can be done for the balance in the top left corner. See https://www.loom.com/share/0967fc3219eb4a6e864e5e2b29ec0aeb.

I'd be happy to pick this task up if possible.

**Comment by Djo1e** [comment]
@secondl1ght @dnlggr 
This is what I came up with so far: https://www.loom.com/share/25e0eb95028e44039c32549084cf622c
Would love to hear opinions - if it looks good I can finalise a PR over the weekend. 

Also, adding a data-fetching library that handles caching (like react-query) we could reuse the data instead of refetching it everytime when navigating between tabs. But that's for a different discussion...

**Comment by secondl1ght** [comment]
Looks nifty!

We need to also make sure that all buttons are disabled until the page loads, a PR would be great.

**Comment by dnlggr** [comment]
> Also, adding a data-fetching library that handles caching (like react-query) we could reuse the data instead of refetching it everytime when navigating between tabs. But that's for a different discussion...

Very good point! We should definitely do this soon. 💯

**Comment by theborakompanioni** [comment]
Merged #203!
