### ISSUE TITLE
Revamp Send, Receive, Earn Screens

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#57]
See [Figma](https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=2850%3A67638). That'll make the screens blend in better with the rest of the fancy new UI.

This is also a good opportunity to think about wording on those screens. E.g. how should we deal with / call the concepts of "Accounts" on the send screen? See discussion [here](https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1?node-id=2850:70953#145075576).

- [x] Send. See #76.
- [x] Receive See https://github.com/joinmarket-webui/joinmarket-webui/pull/85.
- [x] Earn See https://github.com/joinmarket-webui/joinmarket-webui/pull/82.

<table>
<tr>
<td width="30%">
<img width="330" alt="Screenshot 2022-02-07 at 11 09 36" src="https://user-images.githubusercontent.com/10026790/152767958-f31049af-93ba-4e5c-894a-d21c06bc28c2.png">
</td>
<td width="30%">
<img width="320" alt="Screenshot 2022-02-07 at 11 09 47" src="https://user-images.githubusercontent.com/10026790/152767961-fe18395c-3fe4-4e06-a0a8-41389a75d630.png">
</td>
<td width="30%">
<img width="320" alt="Screenshot 2022-02-07 at 11 09 51" src="https://user-images.githubusercontent.com/10026790/152767965-5e8dd870-7539-4602-952c-7197432eafb4.png">
</td>
</tr>
</table>

**Comment by dnlggr** [comment]
Will tackle this tomorrow.

**Comment by theborakompanioni** [comment]
I'll tackle the "Earn" tab, if that's okay.  :rocket:

**Comment by dnlggr** [comment]
Oh "Receive" is missing as well. Will do that.

**Comment by dnlggr** [comment]
Closing this already since PRs for all pages are up now.
