### ISSUE TITLE
Revamp wallet selection screen

### ISSUE THREAD

**Issue by dnlggr** [joinmarket-webui/joinmarket-webui#59]
See [Figma](https://www.figma.com/file/kfejZJFlwBywvLEnPEmJo1?node-id=2850:70953#145075576).

The current screen is fine and works well. The UI in Figma does look a bit better though.

<img width="330" alt="Screenshot 2022-02-07 at 11 20 18" src="https://user-images.githubusercontent.com/10026790/152769488-51196e40-7a4c-492f-862d-7c3d92dc1b29.png">

**Comment by secondl1ght** [comment]
Looks like it only needs some minor changes to match the design, I think I can do this one this week sometime.

**Comment by secondl1ght** [comment]
Started a PR for this #64
