### ISSUE TITLE
Unify API access

### ISSUE THREAD

**Issue by theborakompanioni** [joinmarket-webui/joinmarket-webui#60]
Currently, each API request is assembled and sent by every component itself. As a developer, it would be nice if this could happen clearly from a single service. This makes it easier to understand when, where and why requests are made.

See the [Open API spec for jmwalletd](https://raw.githubusercontent.com/JoinMarket-Org/joinmarket-clientserver/master/docs/api/wallet-rpc.yaml).

I already tried to generate a client from the specification with [openapi-generator](https://github.com/OpenAPITools/openapi-generator). Namely used generator [javascript](https://openapi-generator.tech/docs/generators/javascript),
[javascript-flowtyped](https://openapi-generator.tech/docs/generators/javascript-flowtyped), [typescript](https://openapi-generator.tech/docs/generators/typescript), [typescript-axios](https://openapi-generator.tech/docs/generators/typescript-axios), [typescript-fetch](https://openapi-generator.tech/docs/generators/typescript-fetch). But these look very verbose and bloated, the easiest way is probably just to move all API accesses in one file for now.

What do you think? Any benefits of generating the client at this stage of development? Or is a simple, single file better for now?

**Comment by dnlggr** [comment]
I agree, generating boilerplate code for a network client feels overkill for the couple of calls we have. I think moving the calls to a nice API service would be nice though to keep things a bit separated and DRYed up. 👍
