### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#61]
English only is probably fine for a long while, but at some point having the UI available in multiple languages would be good.

- [x] Apply for Transifex open-source license (Done. Project created: [joinmarket-web-ui](https://www.transifex.com/joinmarket/joinmarket-web-ui/))
- [ ] Integrate [React SDK](https://developers.transifex.com/docs/react-sdk)
- [ ] Replace hard-coded language with translation strings

**Comment by theborakompanioni** [comment]
The sooner we introduce it the better. It becomes more and more difficult the larger the scope becomes. Also, it'd allow non-programmers to contribute to the project. Even if we only support English at the moment, it would already be a good preparation. Does someone dare to try and provide a PR to have something tangible to discuss?

**Comment by dergigi** [comment]
[Transifex](https://www.transifex.com/) is free for open-source projects and is used by Bitcoin Core and BTCPay Server. It also has [native React support](https://medium.com/codex/from-react-i18next-to-transifex-native-migration-guide-3860e96ae8d3).

**Comment by dergigi** [comment]
I just created an open-source project in Transifex: https://www.transifex.com/joinmarket/joinmarket-web-ui/

**Comment by dnlggr** [comment]
Just had a look at the Transifex ReactSDK and it looks like it only supports cloud translations which I don't think is a good fit for this project. What we want is a file containing all localizations which we manually sync with Transifex from time to time (at least before a release). In addition to that we then need some sort of integration that connects the source code to this file.

It seems like Transifex' React tools cannot do that for some reason (I don't know why—seems like they want to push their cloud product), so we need something separate to handle that part. From a quick Google, it looks like [i18n-next](https://github.com/i18next/react-i18next) is a popular tool that could be a fit for that. Will try it out after lunch. Suggestions welcome of course if anyone has experience with that.

**Comment by cstenglein** [comment]
I was trying Transifex for raspiblitz-web, but went to [weblate.org](https://weblate.org/) instead.

I'm using `i18next` in combination with [i18next-react](https://react.i18next.com).

So far I'm happy and if there are some new translations in the code, weblate picks it up itself via a webhook. If there are new translated strings, weblate makes a new PR.

Can only recommend that combination, if you have questions, just ask :)

**Comment by dnlggr** [comment]
Thanks for the tip @cstenglein! I'll definitely check it out seems like it's a good fit for file based react projects.

**Comment by dnlggr** [comment]
Were there any specific reasons that made you switch from Transifex to weblate @cstenglein? Since we haven't _really_ committed to a localization backend yet, your insights could be a valuable input for us at this stage.

On first sight, it seems that while a file based setup with automated sync between GitHub and the localization backend is possible with post solutions, Transifex' main focus seems to be pushing their over-the-air solution while weblate's main focus seems to be the file based, but largely automated flow we actually want. Also, they're a FOSS project at core. I'm actually leaning towards weblate now. 😄 

Any thoughts or strong preferences by anyone here (@dergigi you brought up Transifex initially)?

**Comment by dnlggr** [comment]
> No strong preferences. Transifex came up because both bitcoin-core and BTCPayServer use it, most people seem to be fine with it, and FLOSS projects can use it without charge.

Seems to be working just fine. 👍
