### ISSUE TITLE
Suggestion: reorder and update right navbar icons

### ISSUE THREAD

**Issue by secondl1ght** [joinmarket-webui/joinmarket-webui#68]
This is a small suggestion that I have, I think the icons on the right of the navbar (settings, wallets) should be reordered so that settings is on the right and wallets on the left. I think users will want to access the wallets page more often than the settings so it should be the first one.

One other observation is that the current wallets icon doesn't really let the user know that it links to the wallets page very well. I think it would be better to update this icon to be consistent with other references to the wallets by using the same wallet icon.

Let me know what you guys think about these ideas! Thanks

![image](https://user-images.githubusercontent.com/85003930/153038375-80dc6e85-efd4-4e78-99c1-be3e28212a3f.png)

**Comment by dergigi** [comment]
Random thought: since we have the "Switch wallet" button now, we could remove the button in the navigation bar altogether. 

Random thought 2: we could also do a switch-and-lock when the user presses the button, which would be equivalent of "leaving" the wallet. To me, this would feel more natural than pressing "Lock" every time. You would simply enter the password to "open" (not 'unlock') a wallet, and close it when you were done.

🤔

**Comment by dennisreimann** [comment]
I think Gigi's points are good and would also favor to remove the button if we don't go for point 2. 

Using the list icon might be confusing, because at that position it could resemble the burger menu icon too much.

**Comment by dnlggr** [comment]
> Random thought: since we have the "Switch wallet" button now, we could remove the button in the navigation bar altogether.

Yep that's what I was going for. 😄

**Comment by secondl1ght** [comment]
So if we implement this functionality does that mean we do not need this screen anymore?

![image](https://user-images.githubusercontent.com/85003930/153444916-f67819d2-278d-46f6-a2be-efe80de7162d.png)

We just made updates to it in PR #64, if we remove the wallets button in the top right navbar and make the Switch Wallet button lock when clicked. Then the view that shows the inactive and active wallets with the Open/Lock option will not be part of the app anymore right? Only the Unlock view will be needed?

Just checking that is what we want because we just updated that view to a fresh design.

**Comment by secondl1ght** [comment]
I just noticed that the Switch Wallet button is only visible in magic wallet mode. So if we removed the wallets button in the navbar then users will not be able to switch wallets without first changing modes. Do we want to leave everything how it is? Or add the Switch Wallet button to the advanced mode as well?

**Comment by dnlggr** [comment]
> Do we want to leave everything how it is? Or add the Switch Wallet button to the advanced mode as well?

I'd say they're both valid options for now. I also like the idea of making it an instant lock button. Feel free to pick one and open a PR if you like. :)

**Comment by secondl1ght** [comment]
Ok I think for now maybe it's best to just leave this the way it is - I will close this issue and we can revisit this again later if needed!
