### ISSUE TITLE
Add shields to other views

### ISSUE THREAD

**Issue by secondl1ght** [joinmarket-webui/joinmarket-webui#69]
We talked about in the call today adding the shields to wherever the Accounts are referenced to create a visual link between the accounts and the privacy levels. I just wanted to check that this is what was decided before implementing anything.

**Comment by dergigi** [comment]
Yes, I think showing the shields wherever we sensibly can would be a good idea. I also liked that a better name emerged organically, we seem to be calling them "privacy levels" which works quite well imho.

**Comment by secondl1ght** [comment]
Sounds good, so we can add the shields and also rename them from Accounts to Privacy Level 0 etc.

I will put in a PR for the renaming - for the shields it looks like the only other place the accounts are referenced is in the Send and Receive dropdown selections. 

I looked at the code and it may be hard to add the shields here because these dropdowns are populated by mapping an array of numbers. Does anyone have an idea on how to get them into these dropdowns through refactoring?

**Comment by dergigi** [comment]
Given that we want to [get rid of the shields](https://github.com/joinmarket-webui/joinmarket-webui/wiki/Representation-of-Mixdepths) in the long run, I guess we can close this issue?
