### ISSUE TITLE
Add quiz to make sure that seed was written down

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#74]
Multiple ways to do this, an easy one would be to show an additional screen, pick 3 words at random, force the user to enter these 3 words. 

We could also do it a later point, as suggested in the bitcoin.design guide:

> We recommend that the optimal phase to hint the user to perform the backup should be after the wallet has received funds for the first time. This way, we avoid overwhelming the user with an unnecessary task, as it makes more sense to backup a wallet with funds on it.

Source: https://bitcoin.design/guide/onboarding/backing-up-a-wallet/

**Comment by MaxHillebrand** [comment]
I'd be in favor of allowing to skip the verification process. This is really annoying for people who did take care to write it down properly the first time, and those who just back up the wallet file.

When it is no longer mandatory, I would prefer to then actually test all recovery words. If only 3 random ones are asked, there is still a large potential for error.

**Comment by dergigi** [comment]
> I'd be in favor of allowing to skip the verification process. This is really annoying for people who did take care to write it down properly the first time

That is true, however, we should be careful to understand our target audience and not assume that everyone is an expert or power user. The goal of this project, at least as discussed in the very beginning, is to make it as easy to use as possible, especially for newcomers, i.e. focus on the "Umbrel crowd," so to speak. 

If users can skip something, they will skip it, carelessly, without a second thought. That's how funds are lost.

**Comment by theborakompanioni** [comment]
> If users can skip something, they will skip it, carelessly, without a second thought. That's how funds are lost.

fyi: seed can potentially always be [fetched via api](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/v0.9.5/docs/api/wallet-rpc.yaml#L451).

**Comment by secondl1ght** [comment]
I put in a PR for this #156

**Comment by secondl1ght** [comment]
Closed!
