### ISSUE TITLE
(ui) Implement UTXO Selection Modal 

### ISSUE THREAD

**Issue by amitx13** [joinmarket-webui/joinmarket-webui#765]
subtask of #689 
**Aim** : (ui) Quick freeze/unfreeze UTXOs from selected source Jar

**Description**: Users should have the ability to select specific UTXOs when performing a direct-send or participating in a coin-join. This functionality aims to give users greater control over their UTXOs. We will implement a modal that allows users to select specific UTXOs. This modal should open when the user clicks on the source jar, similar to the interface in /wallet within the Jam application.
![Screenshot from 2024-05-28 10-06-46](https://github.com/joinmarket-webui/jam/assets/112259776/42f67bf9-5eb3-48d3-855f-e60ec8b8b469)

**Objective:**
Provide a quick and simple way for users to freeze or unfreeze UTXOs. Note that this is not full coin control but a simplified version to meet user needs for basic UTXO management.

**Comment by editwentyone** [comment]
@amitx13 what do you think about this? 

behavior: the lower area should be closed when loading the modal, default all green utxos are preselected, the user can now deselect some when needed. the blue area is just for the complete picture 

https://www.figma.com/design/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=6913-17541&t=CTiV3pSEDEFVU3ba-11

<img width="637" alt="image" src="https://github.com/joinmarket-webui/jam/assets/96262473/1c692e62-581d-4a5f-9093-efd1277436e1">

**Comment by editwentyone** [comment]
when selecting the jar we can hint coin control by opening up the Jar and the user can click the jar to start the modal
https://www.figma.com/design/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=5276-74107&t=CTiV3pSEDEFVU3ba-11

<img width="669" alt="image" src="https://github.com/joinmarket-webui/jam/assets/96262473/1d578ab2-be23-4d8e-95f8-b209058b12ad">

**Comment by amitx13** [comment]
Wow, the UI flow looks way cooler now. Thanks for the suggestions, @editwentyone .

**Comment by amitx13** [comment]
Hey , @editwentyone and @theborakompanioni I am done with the flow and also added some checks to give user a bigger picture 
`1. If none of the UTXO's are selected and user tries to proceed `
![Screenshot from 2024-06-02 11-52-34](https://github.com/joinmarket-webui/jam/assets/112259776/aad634cd-15a2-4c99-bf33-f74799283bf0)

`2. If the user tries to Unfreeze UTXO, which is used to create a Fidelity Bond`
![image](https://github.com/joinmarket-webui/jam/assets/112259776/849f46f9-b507-4af6-832b-e1580b3e559b)

`3. In case all the UTXO's are frozen in a jar`
![Screenshot from 2024-06-02 11-52-59](https://github.com/joinmarket-webui/jam/assets/112259776/48acb254-3ec1-46ef-84b8-212095262359)

**Comment by editwentyone** [comment]
case 2 and 3 are solid! good thinking. just add some margin left and right to the whole container, its a little to close to the border

for case 1: instead of a "warning" in red, we could just disable the next button until the user selects minimum one valid UTXO. if that's not enough then lets keep the message but in yellow as a warning, not an error + and the disabled button mechanic 

what do you think? awesome work so far

**Comment by amitx13** [comment]
Thanks for the feedback! Yeah, it's a warning, so going with yellow and disabling the next button is a pretty good idea, tho. Thanks!

**Comment by editwentyone** [comment]
2 other notes:
- the checkboxes are not square and looks "different"? hard to understand if they are selected or not (dark mode tested, easier in light mode)
- if there are no frozen utxos, we don't need the collapse line
- more padding on div.modal-body: from 16 up to ~40?

**Comment by theborakompanioni** [comment]
Just for my understanding.. the goal is "Quick freeze/unfreeze UTXOs from selected source Jar", it is? It feels this comes across like a real "Coin Control" feature, which it is not, right?

**Comment by editwentyone** [comment]
I like to have both realized, quick free unfreeze and coin control 

also you are right, its opening immediately when source is selected. the Figma example above shows how the jar should change after selection to preview that there is a function hidden (by clicking the jar) to bring up the modal

**Comment by editwentyone** [comment]
update with wording (open to other text suggestions), also the labeling of both buttons at the bottom

https://www.figma.com/design/kfejZJFlwBywvLEnPEmJo1/JoinMarket-UI?node-id=6913-17541&t=CnX9tjp55Ds1Y2VB-11

<img width="835" alt="image" src="https://github.com/joinmarket-webui/jam/assets/96262473/2bdf3159-5bbd-4b78-af11-7adee447116a">
