### ISSUE TITLE
No connection to backend: Gateway Timeout

### ISSUE THREAD

**Issue by pretyflaco** [joinmarket-webui/joinmarket-webui#88]
thank you all for spending time and effort to build this. the webUI looks great and I'm excited to test! 

I followed the installation [instructions](https://github.com/joinmarket-webui/joinmarket-webui) and webUI loads locally, however it cannot connect to backend. 

`No connection to backend: Gateway Timeout.` 
![image](https://user-images.githubusercontent.com/32958103/153731042-4195ab25-95fa-4931-bf9e-ea179072c30d.png)

SSL certificate is created and API service is running 
`2022-02-12 22:19:48,932 [INFO]  Starting jmwalletd on port: 28183`
`2022-02-12 22:19:48,946 [INFO]  Joinmarket daemon listening on port 27183`

Joinmarket version: v.0.9.4.-85-gfd5871b

In local terminal, two errors show up after
`npm start`
 
the second error is recurring

> [HPM] Error occurred while proxying request localhost:3000/api/v1/wallet/all to https://localhost:28183/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
> 
> [HPM] Error occurred while proxying request localhost:3000/api/v1/session to https://localhost:28183/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)

The error comes up no matter if API Service is running or not, and error occurs when requesting to `to https://localhost:28183/` - however shouldn't the request be to raspiblitz `192.168.0.103:28183` ?

**Comment by theborakompanioni** [comment]
> thank you all for spending time and effort to build this. the webUI looks great and I'm excited to test!

Thank you for testing! :rocket:
Do not hold back any of your findinds - any feedback is highly appreciated.

> The error comes up no matter if API Service is running or not, and error occurs when requesting to `to https://localhost:28183/` - however shouldn't the request be to raspiblitz `192.168.0.103:28183` ?

Yes, it should go to https://localhost:28183 as the connection is tunneled to your raspiblitz.
This sounds like the ssh tunnel is not established. Can you make sure that `localhost:28183` is tunneled to your raspiblitz at `192.168.0.103:28183`? 

Alternatively I guess you can adapt `src/setupProxy.js` to your needs as a workaround - but the above approach should be preferred.

Hope this helps!
Thank you.

**Comment by pretyflaco** [comment]
thanks for the hint. SSH tunnel was the issue indeed. Changing config from 

Host raspiblitz
  HostName 192.168.0.103
  User admin
  ForwardAgent yes
  LocalForward 28183 localhost:28183

to

Host raspiblitz
  HostName 192.168.0.103
  User joinmarket
  ForwardAgent yes
  LocalForward 28183 localhost:28183

solved it.
