### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#9]
Dark Mode support is basically required nowadays, otherwise the dark mode maximalists will rip us apart. A day/night toggle should be good for starters. We can also do day/night/dusk as seen in the Thunderhub UI:

<img width="142" alt="Screenshot 2022-01-24 at 11 37 31" src="https://user-images.githubusercontent.com/109058/150767817-ef1747ee-a341-4e40-b227-af0869f8fd04.png">

**Comment by dennisreimann** [comment]
I think we'd need a custom Bootstrap version for that -- I got plenty of experience through what I did in that regard for BTCPay.

**Comment by GBKS** [comment]
I'd prefer not having a toggle in the main UI, but putting it in the settings page. Don't think it's something that warrants visibility at all times in the main nav.

By default, we can detect the OS preference of color theme via CSS, and also react accordingly if that value changes. And users can adjust it in the settings if they want to.

**Comment by dennisreimann** [comment]
@GBKS +1 on the settings screen. Using the system preference as the default is already implemented :)
