### ISSUE TITLE
Parts of an address might be rendered as math

### ISSUE THREAD

**Issue by dergigi** [joinmarket-webui/joinmarket-webui#96]
Just noticed a small issue: if an address contains an "x" between two numbers it will be rendered as a mathematical symbol:

<img width="678" alt="Screenshot 2022-02-15 at 11 18 21" src="https://user-images.githubusercontent.com/109058/154041798-aecd7792-eb5d-4e5e-be24-118ddf65e096.png">

An easy fix would be to render every address inside a `<code>` tag or something, like this: `bcrt1q6wyvqnm2daajashl0jdl8l84ghwadsg4g37x30`

**Comment by dnlggr** [comment]
This is Inter's [contextual alternates font feature](https://rsms.me/inter/#features/calt). I'll turn that off. Didn't know it was on by default. 🤔
